<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><AllowUnsafeBlocks>true</AllowUnsafeBlocks></PropertyGroup>
  <ItemGroup><PackageReference Include="TorchSharp" /></ItemGroup>
  <ItemGroup><ProjectReference Include="../ComfySharp.Tokenization/ComfySharp.Tokenization.csproj" /></ItemGroup>
  <ItemGroup><EmbeddedResource Include="unet-training-order.json" /></ItemGroup>
</Project>
