<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/ComfySharp.Nodes/ComfySharp.Nodes.csproj" /></ItemGroup>
  <ItemGroup><ProjectReference Include="../../src/ComfySharp.Nodes.Tensor/ComfySharp.Nodes.Tensor.csproj" /></ItemGroup>
</Project>
